Section "Device"
    Identifier  "DummyDevice"
    Driver      "dummy"
EndSection

Section "Monitor"
    Identifier "Monitor0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "DummyDevice"
    Monitor    "Monitor0"
    DefaultDepth 24

    SubSection "Display"
        Depth 24
        Modes "1920x1080" "1600x1000" "1600x900"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "Layout0"
    Screen 0 "Screen0"
EndSection
